# Generated by Django 4.2.1 on 2023-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='afficher',
            new_name='show',
        ),
        migrations.AddField(
            model_name='category',
            name='productLen',
            field=models.IntegerField(default=0),
        ),
    ]
